### ISSUE TITLE
There are multiple heroes that share the same tag within a subtree

### ISSUE THREAD

**Issue by theobouwman** [goposse/fluro#10]
When I try to start a new page with:
```
Application.get().router.navigateTo(context, "/contract?contract-uuid=$contractUUID");
```
I get this error:
```
I/flutter (13538): ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (13538): The following assertion was thrown during a scheduler callback:
I/flutter (13538): There are multiple heroes that share the same tag within a subtree.
I/flutter (13538): Within each subtree for which heroes are to be animated (typically a PageRoute subtree), each Hero
I/flutter (13538): must have a unique non-null tag.
I/flutter (13538): In this case, multiple heroes had the tag "Instance of 'Object'".
I/flutter (13538):
I/flutter (13538): When the exception was thrown, this was the stack:
I/flutter (13538): #0      Hero._allHeroesFor.visitor.<anonymous closure> (package:flutter/src/widgets/heroes.dart:114:13)
I/flutter (13538): #2      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:112:16)
I/flutter (13538): #3      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #4      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #5      MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4506:16)
I/flutter (13538): #6      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #7      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #8      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #9      SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4406:14)
I/flutter (13538): #10     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #11     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #12     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #13     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #14     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #15     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #16     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #17     List.forEach (dart:core-patch/growable_array.dart:267)
I/flutter (13538): #18     SliverMultiBoxAdaptorElement.visitChildren (package:flutter/src/widgets/sliver.dart:866:36)
I/flutter (13538): #19     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #20     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4506:16)
I/flutter (13538): #21     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #22     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #23     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #24     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4406:14)
I/flutter (13538): #25     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #26     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4406:14)
I/flutter (13538): #27     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #28     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4406:14)
I/flutter (13538): #29     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #30     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #31     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #32     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4406:14)
I/flutter (13538): #33     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #34     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4406:14)
I/flutter (13538): #35     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #36     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4406:14)
I/flutter (13538): #37     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #38     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #39     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #40     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #41     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #42     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #43     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #44     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #45     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #46     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #47     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #48     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #49     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #50     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4506:16)
I/flutter (13538): #51     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #52     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #53     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #54     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #55     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #56     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4406:14)
I/flutter (13538): #57     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #58     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #59     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #60     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4406:14)
I/flutter (13538): #61     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #62     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #63     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #64     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #65     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #66     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4406:14)
I/flutter (13538): #67     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #68     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #69     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #70     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #71     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #72     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #73     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #74     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #75     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #76     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #77     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #78     List.forEach (dart:core-patch/growable_array.dart:267)
I/flutter (13538): #79     SliverMultiBoxAdaptorElement.visitChildren (package:flutter/src/widgets/sliver.dart:866:36)
I/flutter (13538): #80     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #81     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4406:14)
I/flutter (13538): #82     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #83     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4506:16)
I/flutter (13538): #84     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #85     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #86     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #87     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4406:14)
I/flutter (13538): #88     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #89     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4406:14)
I/flutter (13538): #90     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #91     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4406:14)
I/flutter (13538): #92     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #93     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #94     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #95     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4406:14)
I/flutter (13538): #96     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #97     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4406:14)
I/flutter (13538): #98     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #99     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4406:14)
I/flutter (13538): #100    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #101    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #102    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #103    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #104    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #105    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #106    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #107    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #108    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #109    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #110    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #111    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #112    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #113    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #114    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #115    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #116    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #117    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #118    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #119    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #120    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #121    MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4506:16)
I/flutter (13538): #122    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #123    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #124    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #125    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #126    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #127    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4406:14)
I/flutter (13538): #128    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #129    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #130    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #131    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4406:14)
I/flutter (13538): #132    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #133    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #134    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #135    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #136    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #137    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #138    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #139    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #140    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #141    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #142    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #143    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #144    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #145    MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4506:16)
I/flutter (13538): #146    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #147    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #148    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #149    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #150    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #151    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4406:14)
I/flutter (13538): #152    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #153    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #154    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #155    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4406:14)
I/flutter (13538): #156    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #157    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #158    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #159    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #160    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #161    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #162    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #163    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #164    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #165    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #166    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #167    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #168    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #169    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #170    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #171    MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4506:16)
I/flutter (13538): #172    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #173    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #174    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #175    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #176    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #177    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4406:14)
I/flutter (13538): #178    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #179    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #180    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #181    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4406:14)
I/flutter (13538): #182    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #183    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #184    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #185    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #186    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #187    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #188    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #189    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #190    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #191    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #192    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #193    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #194    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #195    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #196    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:126:15)
I/flutter (13538): #197    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3470:14)
I/flutter (13538): #198    Element.visitChildElements (package:flutter/src/widgets/framework.dart:2528:5)
I/flutter (13538): #199    Hero._allHeroesFor (package:flutter/src/widgets/heroes.dart:128:13)
I/flutter (13538): #200    HeroController._startHeroTransition (package:flutter/src/widgets/heroes.dart:480:53)
I/flutter (13538): #201    HeroController._maybeStartHeroTransition.<anonymous closure> (package:flutter/src/widgets/heroes.dart:462:9)
I/flutter (13538): #202    BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:688:15)
I/flutter (13538): #203    BindingBase&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:644:9)
I/flutter (13538): #204    _invoke (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:86)
I/flutter (13538): #205    _drawFrame (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:75)
I/flutter (13538): (elided one frame from class _AssertionError)
I/flutter (13538): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (13538): Another exception was thrown: There are multiple heroes that share the same tag within a subtree.
```

But when I start it from another place in the app I won't get this error

**Comment by theobouwman** [comment]
This is not a Fluro bug => https://groups.google.com/forum/#!topic/flutter-dev/ZreLZ-IM8Wo
