### ISSUE TITLE
Transition type fadeIn animation type works, inFromLeft does not

### ISSUE THREAD

**Issue by ride4sun** [goposse/fluro#21]
this works:
`  router.navigateTo(context, _routeName, transition: TransitionType.fadeIn); `

this does not:
`router.navigateTo(context, _routeName, transition: TransitionType.inFromLeft);`

```
[+3999 ms] I/flutter (20265): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
[  +18 ms] I/flutter (20265): The following assertion was thrown building
[   +1 ms] I/flutter (20265): _ModalScope-[LabeledGlobalKey<_ModalScopeState>#a7c09](dirty, state: _ModalScopeState#805cf):
[        ] I/flutter (20265): type '_AnimatedEvaluation<Offset>' is not a subtype of type 'Animation<FractionalOffsetGeometry>' of
[        ] I/flutter (20265): 'position' where
[        ] I/flutter (20265):   _AnimatedEvaluation is from package:flutter/src/animation/tween.dart
[        ] I/flutter (20265):   Offset is from dart:ui
[        ] I/flutter (20265):   double is from dart:core
[        ] I/flutter (20265):   Offset is from dart:ui
[        ] I/flutter (20265):   Animation is from package:flutter/src/animation/animation.dart
[        ] I/flutter (20265):   FractionalOffsetGeometry is from package:flutter/src/painting/fractional_offset.dart
[  +23 ms] I/flutter (20265): Either the assertion indicates an error in the framework itself, or we should provide substantially
[        ] I/flutter (20265): more information in this error message to help you determine and fix the underlying cause.
[        ] I/flutter (20265): In either case, please report this assertion by filing a bug on GitHub:
[        ] I/flutter (20265):   https://github.com/flutter/flutter/issues/new
[        ] I/flutter (20265): When the exception was thrown, this was the stack:
[  +18 ms] I/flutter (20265): #0      new SlideTransition (package:flutter/src/widgets/transitions.dart:106)
[   +1 ms] I/flutter (20265): #1      Router._standardTransitionsBuilder.<anonymous closure> (package:fluro/src/router.dart:138)
[        ] I/flutter (20265): #2      PageRouteBuilder.buildTransitions (package:flutter/src/widgets/pages.dart:121)
[        ] I/flutter (20265): #3      _ModalScopeState.build (package:flutter/src/widgets/routes.dart:469)
[        ] I/flutter (20265): #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:3646)
[        ] I/flutter (20265): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3556)
[        ] I/flutter (20265): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3457)
[        ] I/flutter (20265): #7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3536)
[        ] I/flutter (20265): #8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3674)
[        ] I/flutter (20265): #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3531)
[        ] I/flutter (20265): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2900)
[        ] I/flutter (20265): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2703)
[        ] I/flutter (20265): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3568)
[        ] I/flutter (20265): #13     Element.rebuild (package:flutter/src/widgets/framework.dart:3457)
[   +6 ms] I/flutter (20265): #14     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3536)
[        ] I/flutter (20265): #15     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3674)
[        ] I/flutter (20265): #16     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3531)
[        ] I/flutter (20265): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2900)
[        ] I/flutter (20265): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2703)
[        ] I/flutter (20265): #19     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4330)
[        ] I/flutter (20265): #20     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4653)
[        ] I/flutter (20265): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2692)
[        ] I/flutter (20265): #22     _TheatreElement.update (package:flutter/src/widgets/overlay.dart:507)
[        ] I/flutter (20265): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2692)
[        ] I/flutter (20265): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3568)
[        ] I/flutter (20265): #25     Element.rebuild (package:flutter/src/widgets/framework.dart:3457)
[        ] I/flutter (20265): #26     StatefulElement.update (package:flutter/src/widgets/framework.dart:3693)
[        ] I/flutter (20265): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2692)
[        ] I/flutter (20265): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3568)
[        ] I/flutter (20265): #29     Element.rebuild (package:flutter/src/widgets/framework.dart:3457)
[        ] I/flutter (20265): #30     ProxyElement.update (package:flutter/src/widgets/framework.dart:3803)
[        ] I/flutter (20265): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2692)
[        ] I/flutter (20265): #32     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4545)
[        ] I/flutter (20265): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2692)
[        ] I/flutter (20265): #34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3568)
[        ] I/flutter (20265): #35     Element.rebuild (package:flutter/src/widgets/framework.dart:3457)
[        ] I/flutter (20265): #36     StatefulElement.update (package:flutter/src/widgets/framework.dart:3693)
[        ] I/flutter (20265): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2692)
[        ] I/flutter (20265): #38     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4545)
[        ] I/flutter (20265): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2692)
[        ] I/flutter (20265): #40     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4545)
[        ] I/flutter (20265): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2692)
[        ] I/flutter (20265): #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3568)
[        ] I/flutter (20265): #43     Element.rebuild (package:flutter/src/widgets/framework.dart:3457)
[        ] I/flutter (20265): #44     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2261)
[        ] I/flutter (20265): #45     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:530)
[        ] I/flutter (20265): #46     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:194)
[        ] I/flutter (20265): #47     BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:713)
[        ] I/flutter (20265): #48     BindingBase&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:649)
[        ] I/flutter (20265): #49     _invoke (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:86)
[        ] I/flutter (20265): #50     _drawFrame (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:75)
[        ] I/flutter (20265): ════════════════════════════════════════════════════════════════════════════════════════════════════
[ +216 ms] I/flutter (20265): 4 2017-10-10 15:13:26.535204 FINE rx.logging_middleware RxAppActions-activeScreenChanged: /switchFamilyScreen
[  +22 ms] I/flutter (20265): Another exception was thrown: type '_AnimatedEvaluation<Offset>' is not a subtype of type 'Animation<FractionalOffsetGeometry>' of 'position' where
[ +262 ms] I/flutter (20265): 5 2017-10-10 15:13:26.821407 FINE rx.logging_middleware RxAppActions-activeScreenChanged: /switchFamilyScreen
```

**Comment by alardizabal** [comment]
Can you update to `1.2.1`? There was a breaking change in Flutter but I just tested `inFromLeft` and it works with the update.

**Comment by ride4sun** [comment]
I did that already

**Comment by lukef** [comment]
@ride4sun - are you still encountering issues? If so we will investigate. Sorry for the delay.

**Comment by ride4sun** [comment]
I stopped using the lib because of the issue. I would like to again when it gets fixed.

**Comment by lukef** [comment]
This seems to be working on the latest version in the example project. It might be worth trying the latest update and reopening if the issue is still present so we can get more info on your implementation.
