### ISSUE TITLE
error: Unsupported tag at this point: 2

### ISSUE THREAD

**Issue by g33kidd** [goposse/fluro#42]
Hello, I have just started using Fluro, but I can't use it with Hot Reloading for some reason. Every time I make a change while I am on a route that I have navigated to, it just gives me this error. Here is some more information.

Unless I'm missing something, I have no idea what could be causing this issue.

**Note** this happens only when a hot reload is performed.

I have also gotten the error message `Unsupported tag at this point: 0.`

```
I/flutter (15498): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (15498): The following _CompileTimeError was thrown building
I/flutter (15498): _OverlayEntry-[LabeledGlobalKey<_OverlayEntryState>#5973d](dirty, state: _OverlayEntryState#352c7):
I/flutter (15498): error: Unsupported tag at this point: 2.
I/flutter (15498): 
I/flutter (15498): When the exception was thrown, this was the stack:
I/flutter (15498): #0      Router.matchRoute.<anonymous closure>.<anonymous closure> (file:///Users/g33kidd/.pub-cache/hosted/pub.dartlang.org/fluro-1.3.0/lib/src/router.dart:118:28)
I/flutter (15498): #1      PageRouteBuilder.buildPage (package:flutter/src/widgets/pages.dart:120:12)
I/flutter (15498): #2      ModalRoute._buildModalScope (package:flutter/src/widgets/routes.dart:1027:13)
I/flutter (15498): #3      _OverlayEntryState.build (package:flutter/src/widgets/overlay.dart:170:25)
I/flutter (15498): #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:3713:27)
I/flutter (15498): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3625:15)
I/flutter (15498): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (15498): #7      StatefulElement.update (package:flutter/src/widgets/framework.dart:3760:5)
I/flutter (15498): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (15498): #9      RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4340:32)
I/flutter (15498): #10     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4726:17)
I/flutter (15498): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (15498): #12     _TheatreElement.update (package:flutter/src/widgets/overlay.dart:507:16)
I/flutter (15498): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (15498): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (15498): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (15498): #16     StatefulElement.update (package:flutter/src/widgets/framework.dart:3760:5)
I/flutter (15498): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (15498): #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (15498): #19     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (15498): #20     ProxyElement.update (package:flutter/src/widgets/framework.dart:3870:5)
I/flutter (15498): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (15498): #22     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4618:14)
I/flutter (15498): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (15498): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (15498): #25     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (15498): #26     StatefulElement.update (package:flutter/src/widgets/framework.dart:3760:5)
I/flutter (15498): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (15498): #28     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4618:14)
I/flutter (15498): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (15498): #30     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4618:14)
I/flutter (15498): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (15498): #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (15498): #33     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (15498): #34     StatefulElement.update (package:flutter/src/widgets/framework.dart:3760:5)
I/flutter (15498): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (15498): #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (15498): #37     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (15498): #38     ProxyElement.update (package:flutter/src/widgets/framework.dart:3870:5)
I/flutter (15498): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (15498): #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (15498): #41     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (15498): #42     StatelessElement.update (package:flutter/src/widgets/framework.dart:3685:5)
I/flutter (15498): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (15498): #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (15498): #45     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (15498): #46     ProxyElement.update (package:flutter/src/widgets/framework.dart:3870:5)
I/flutter (15498): #47     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (15498): #48     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (15498): #49     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (15498): #50     ProxyElement.update (package:flutter/src/widgets/framework.dart:3870:5)
I/flutter (15498): #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (15498): #52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (15498): #53     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (15498): #54     StatefulElement.update (package:flutter/src/widgets/framework.dart:3760:5)
I/flutter (15498): #55     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (15498): #56     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (15498): #57     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (15498): #58     ProxyElement.update (package:flutter/src/widgets/framework.dart:3870:5)
I/flutter (15498): #59     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (15498): #60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (15498): #61     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (15498): #62     StatefulElement.update (package:flutter/src/widgets/framework.dart:3760:5)
I/flutter (15498): #63     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (15498): #64     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (15498): #65     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (15498): #66     ProxyElement.update (package:flutter/src/widgets/framework.dart:3870:5)
I/flutter (15498): #67     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (15498): #68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (15498): #69     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (15498): #70     ProxyElement.update (package:flutter/src/widgets/framework.dart:3870:5)
I/flutter (15498): #71     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (15498): #72     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (15498): #73     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (15498): #74     StatelessElement.update (package:flutter/src/widgets/framework.dart:3685:5)
I/flutter (15498): #75     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (15498): #76     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (15498): #77     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (15498): #78     StatefulElement.update (package:flutter/src/widgets/framework.dart:3760:5)
I/flutter (15498): #79     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (15498): #80     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (15498): #81     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (15498): #82     ProxyElement.update (package:flutter/src/widgets/framework.dart:3870:5)
I/flutter (15498): #83     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (15498): #84     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (15498): #85     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (15498): #86     StatefulElement.update (package:flutter/src/widgets/framework.dart:3760:5)
I/flutter (15498): #87     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (15498): #88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (15498): #89     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (15498): #90     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2225:33)
I/flutter (15498): #91     ______BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:621:20)
I/flutter (15498): #92     _____BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (15498): #93     ___BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (15498): #94     ___BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (15498): #95     ___BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter (15498): #97     _Timer._runTimers (dart:isolate/timer_impl.dart:382:19)
I/flutter (15498): #98     _Timer._handleMessage (dart:isolate/timer_impl.dart:416:5)
I/flutter (15498): #99     _RawReceivePortImpl._handleMessage (dart:isolate/isolate_patch.dart:165:12)
I/flutter (15498): (elided one frame from package dart:async)
I/flutter (15498): ════════════════════════════════════════════════════════════════════════════════════════════════════

```

**Comment by g33kidd** [comment]
After disabling `--preview-dart-2` in Android Studio, it seems this is no longer an issue. Though, it's still an issue in Dart 2 Preview.

**Comment by lukef** [comment]
This may have been a flutter issue and not related to fluro. Can you take a look at https://github.com/flutter/flutter/issues/15214 and let me know if this is your issue?

**Comment by lukef** [comment]
Going to close this as it is likely related to the aforementioned issue. Feel free to reopen as necessary.
